#!/bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2014 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract: search personal phonebook for a pattern
#
# shellcheck disable=SC1090
. "$LIBSH"

@import stdio
@import getopt

# Defaults {{{1
#
VERSION='1.0'
PHONEBOOK=${XDG_CONFIG_HOME:-"$HOME/etc"}/phonebook

# Documentation {{{1
#
# shellcheck disable=SC2120
print_help() (
    [ -n "$1" ] && printf "%s\n" "$1"

    cat <<EOF
Usage: $(basename "$0") [OPTION] STRING
Look for an entry in a phonebook

STRING is the string to search for

 -v | --version display version info and exit
 -h | --help    display this help and exit
EOF
) >&2

print_version() (
    cat <<EOF
$(basename "$0") $VERSION

Copyright (C) 2014 Orion Arts
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Jeremy Brubaker.
EOF
) >&2

# Process options {{{1
#
parse_error() {
    case $2 in
        unknown) print_help "unknown option: $3" ;;
        required) print_help "$3 requires an argument" ;;
    esac
    return 1
}

parser() {
    setup REST error:parse_error
    param PHONEBOOK      -f --phonebook -- "phonebook"
    disp  :print_help    -h --help
    disp  :print_version -v --version
}

eval "$(getoptions parser - "$0")"

[ -r "$PHONEBOOK" ] || 
    stdio::die 1 "%s: phonebook not found: %s" "$0" "$PHONEBOOK"

# Main {{{1
#
grep -i "$@" "$PHONEBOOK"

