#!/usr/bin/awk -f
#
# Copyright 2014 Jeremy Brubaker <jbru362@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#
# put commas in numbers
# input: a number per line
# output: the number with commas, rounded to two decimal places

    { printf("%s\n", addcomma($0)) }

function addcomma(x,    sum) {
    if (x < 0)
        return "-" addcomma(-x)

    num = sprintf("%.2f", x)

    while (num ~ /[0-9][0-9][0-9][0-9]/)
        sub(/[0-9][0-9][0-9][,.]/, ",&", num)

    return num
}
