#!/usr/bin/awk -f
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2014 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract: put commas in numbers
# input: a number per line
#

    { printf("%s\n", addcomma($0)) }

function addcomma(x,    sum) {
    if (x < 0)
        return "-" addcomma(-x)

    # Split into integer and fractional parts
    ipart = int(x)
    fpart = sprintf("%f", x) - ipart
    # Remove leading 0 (or delete it if fpart == 0)
    sub(/^0/, "", fpart)

    while (ipart ~ /[0-9]{4}/)
        sub(/[0-9]{3}(,|$)/, ",&", ipart)

    return ipart fpart
}

