#!/bin/sh
# Usage: addr [<if>]
# Show IPv4 address for interface <if> or all interfaces with
# no <if> given.
#
# (C) 2010 Ryan Tomayko <tomayko.com>

/sbin/ifconfig -a $1     |
grep 'inet '       |
grep Bcast         |
sed 's/addr://'    |
awk '{ print $2 }'
