#!/bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2022 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract: add an SSH public key to an "allowed signers" file
#
# Usage: addsigner < <file with one public key per line>
#

allowed_signers="$HOME/.ssh/allowed_signers"

while read type key id; do
    printf "%s namespaces=\"file\" %s %s\n" "$id" "$type" "$key" >> "$allowed_signers"
done

