#!/bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2025 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract-atwork: Return true if WiFi is connected to anything in $WORK_SSID
# abstract-atworkd: Daemon to set status for atwork to query
#
# Defaults {{{1
#
if [ "$(id -u)" -eq 0 ]; then
    ATWORK_FILE_DFLT=/var/cache/atwork
else
    ATWORK_FILE_DFLT=${XDG_CACHE_HOME:-"$HOME/.cache"}/atwork
fi

# Documentation {{{1
#
VERSION='1.0'

print_help() (
    [ -n "$1" ] && printf "%s\n" "$1"

    case $(basename "$0") in
        atwork)
            cat <<END
Usage: $0 [OPTION]

Check if connected to an SSID found in \$WORK_SSID

  -f [FILE] use FILE as the marker (Default: $ATWORK_FILE_DFLT)
  -h   	    display this help and exit
  -V        output version information and exit
END
            ;;
        atworkd)
            cat <<END
Usage: $0 [OPTION]

Continually check if connected to an SSID found in \$WORK_SSID

  -f [FILE] use FILE as the marker (Default: $ATWORK_FILE_DFLT)
  -h   	    display this help and exit
  -V        output version information and exit
END
            ;;
    esac
) >&2

print_version() (
    cat <<END
$0 $VERSION
Copyright (C) 2025 Orion Arts
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Jeremy Brubaker.
END
) >&2

# Process options {{{1
#
ATWORK_FILE=$ATWORK_FILE_DFLT
while getopts ':fhV' c; do
    case $c in
        f) ATWORK_FILE=$OPTARG ;;
        h) print_help; exit 0 ;;
        V) print_version; exit 0 ;;
        ?) print_help "Invalid option: -$OPTARG";  exit 1 ;;
    esac
done
shift $((OPTIND-1))
OPTIND=1

# Main {{{1
#
case $(basename $0) in
    atwork)
        if pgrep atworkd >/dev/null; then
            [ -f "$ATWORK_FILE" ]
        else
            printf 'atworkd not running. To be safe you are currently "at work"\n'
            false
        fi
        ;;

    atworkd)
        while true; do
            if echo "$WORK_SSID" | grep -qs \
                "\<$(nmcli dev wifi show 2>/dev/null | grep SSID | cut -d' ' -f2)\>"; then

            touch "$ATWORK_FILE"
        else
            rm -f "$ATWORK_FILE"
            fi
            sleep 10
        done
        ;;
esac

