#!/bin/bash
#
# Look busy while your system lets the boss know you are waiting
# on package installs
#
# Requires dialog(1) for the output and yum(1) to get a list of packages

### Configurable settings
#
PERCENT_DELTA_START=10
PERCENT_DELTA=5
PERCENT_DELTA_MIN=1
TIME_MS_MIN=25
TIME_MS_MAX=100
BOX_LINES=6
BOX_COLS=65 # This should be fairly large to keep package names visible
### End configurable settings

PROGNAME=$(basename "$0")
TMPFILE=$(mktemp "$PROGNAME.XXXXXX")
trap 'rm -f "$TMPFILE"' EXIT

exec 3<>"$TMPFILE"
rm "$TMPFILE"

random()
{
    awk -v min="$1" -v max="$2" 'BEGIN{srand(); print int(min+rand()*(max-min+1))}'
}

get_pkg_name()
{
    # Get a random letter
    c=$(random 97 122) # 97-122: lowercase letter range
    c=$(printf \\$(printf '%03o' $c))

    # Get a random package name that starts with that letter
    echo "$(yum list | grep -E "^$c" | awk '{print $1}' | shuf -n1)"
}

part=1
pkg="Preparing..."
while true; do
    # Get the next package name in the background
    get_pkg_name >/dev/fd/3 &

    i=0
    delta=$PERCENT_DELTA_START
    while test $i -lt 100; do
        # Send new % complete to output
        echo $i

        # Increase % by last change +/-5%
        delta=$(random $((delta-PERCENT_DELTA)) $((delta+PERCENT_DELTA)))
        test "$delta" -lt "$PERCENT_DELTA_MIN" && delta="$PERCENT_DELTA_MIN"
        i=$(( i+delta ))

        # Delay a random time
        time=$(random $TIME_MS_MIN $TIME_MS_MAX)
        sleep $((TIME_MS_MAX / time));
    done | dialog --gauge "$pkg" $BOX_LINES $BOX_COLS;

    # Block for a new package name
    IFS= read -r pkg </dev/fd/3
    pkg="Install part $part : $pkg"
    part=$(( part+1 ))
done

