#!/bin/sh
#
# Add clipboard contents as a buku bookmark
#
# Place in PATH and createt a keybinding to run bukuadd

if command -v xclip >/dev/null; then
    cmd=xclip
elif command -v xsel >/dev/null; then
    cmd=xsel
else
    exit
fi

"$cmd" | buku -a

