#!/bin/sh
#
# cal: cal(1) wrapper with a nicer interface
#
# Usage: cal [month [year]] [cal(1) options]
#

# Separate options and arguments
#
for i
do
    case $i in
        -h)
            echo "Usage: cal [moth [year]] [options]"
            exit
            ;;
        -*) opts="$opts $i" ;;
        *) args="$args $i" ;;
    esac
done

# Process args if we have any
if test "$args"
then
    set $args # put args in $*
    case $# in
        1) m=$1; set `date`; y=$6 ;; # 1 arg; use this year
        *) m=$1; y=$2 ;;
    esac
fi

# Convert month arg to a number
#
case $m in
        [jJ]an*) m=1 ;;
        [fF]eb*) m=2 ;;
        [mM]ar*) m=3 ;;
        [aA]pr*) m=4 ;;
        [mM]ay*) m=5 ;;
        [jJ]un*) m=6 ;;
        [jJ]ul*) m=7 ;;
        [aA]ug*) m=8 ;;
        [sS]ep*) m=9 ;;
        [oO]ct*) m=10 ;;
        [nN]ov*) m=11 ;;
        [dD]ec*) m=12 ;;
        *) y=$m; m="" ;; # plain year
    esac

/usr/bin/cal $opts $m $y

