#!/bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2014 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract: cal(1) wrapper with a nicer interface
#
# Usage: cal [month [year]] [cal(1) options]
#

# Separate options and arguments
#
for i
do
    case $i in
        -h)
            echo "Usage: cal [moth [year]] [options]"
            exit
            ;;
        -*) opts="$opts $i" ;;
        *) args="$args $i" ;;
    esac
done

# Process args if we have any
if test "$args"
then
    set $args # put args in $*
    case $# in
        1) m=$1; set `date`; y=$6 ;; # 1 arg; use this year
        *) m=$1; y=$2 ;;
    esac
fi

# Convert month arg to a number
#
case $m in
        [jJ]an*) m=1 ;;
        [fF]eb*) m=2 ;;
        [mM]ar*) m=3 ;;
        [aA]pr*) m=4 ;;
        [mM]ay*) m=5 ;;
        [jJ]un*) m=6 ;;
        [jJ]ul*) m=7 ;;
        [aA]ug*) m=8 ;;
        [sS]ep*) m=9 ;;
        [oO]ct*) m=10 ;;
        [nN]ov*) m=11 ;;
        [dD]ec*) m=12 ;;
        *) y=$m; m="" ;; # plain year
    esac

/usr/bin/cal $opts $m $y

