#!/bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2021 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract: change screen brightness
#
# Requires: brightnessctl, dunst
#

# Arbitrary but unique message id for dunst
msg_id=272472

case "$1" in
    +*) sign='+' ;;
    -*) sign='-' ;;
    *) exit 1 ;;
esac
amt=$(echo $1 | tr -d '%+-')

for d in $(brightnessctl -l | grep backlight | cut -d' ' -f2 | tr -d "'"); do
    brightnessctl -q -d $d set "$amt%$sign"
    max=$(brightnessctl -d $d max)
    cur=$(brightnessctl -d $d get)
    current_percentage=$(echo "scale=2; $cur / $max" | bc -l | tr -d '.')
done

dunstify -a "changeBrightness" -u low \
    -r "$msg_id" -h "int:value:$current_percentage" "Brightness: ${current_percentage}%"

