#!/bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2021 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract: change volume
#
# Requires (wpctl | pactl) and dunst
#

# Arbitrary but unique message id for dunst
msg_id=991049

if command -v wpctl >/dev/null; then

    case "$1" in
        mute)
            wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
            if wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -q MUTED; then
                is_muted=yes
            else
                is_muted=no
            fi
            ;;
        +*|-*)
            sign=$(echo "$1" | cut -c1)
            amnt=$(echo "$1" | cut -c2-)

            wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ "$amnt$sign"
            ;;
    esac
    current_volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ |
        cut -d' ' -f2 | sed -e 's/^0//' -e 's/\.//')
elif command -v pactl >/dev/null; then
    default_sink=$(LC_ALL=C pactl list sinks short | \
        grep "$(\
            pactl info | 
            grep "Default Sink" | 
            sed 's/[^:]*: //')" | 
            cut -f1)

    case "$@" in
        mute)
            pactl set-sink-mute @DEFAULT_SINK@ toggle
            is_muted=$(LC_ALL=C pactl list sinks | \
                grep -A9 "Sink #$default_sink" | \
                grep Mute | \
                awk '{print $2}')
            ;;
        +*|-*)
            pactl set-sink-volume @DEFAULT_SINK@ "$@"
            ;;
        *) exit 1 ;;
    esac

    current_volume=$(LC_ALL=C pactl list sinks | \
        grep -A9 "Sink #$default_sink" | 
        grep Volume | 
        awk '{print $5}' | 
        tr -dc '[:digit:]')
else
    printf '%s\n' 'Neither wpctl or pactl found' >&2
    exit 1
fi

if [ "$current_volume" = "0" ] || [ "$is_muted" = "yes" ]; then
    dunstify -a "changeVolume" -u low -i audio-volume-muted \
             -r "$msg_id" "Volume muted" 
else
    dunstify -a "changeVolume" -u low -i audio-volume-high \
        -r "$msg_id" -h int:value:"$current_volume" "Volume: ${current_volume}%"
fi

