#!/bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2021 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract: verify a SSH-key signed file
#
# Usage: chksign <filename> <signers email>
#

allowed_signers="$HOME/.ssh/allowed_signers"

if [ -z "$1" ]; then
    printf "No filename to check provided. Exiting\n" >&2
    exit 1
fi

if [ -z "$2" ]; then
    printf "No signer email provided. Exiting\n" >&2
    exit 1
fi

sig="$1.sig"

ssh-keygen -Y verify -f "$allowed_signers" -I "$2" -n file -s "$sig" < "$1"

