#!/bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2021 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract: use rclonesync to sync cloud storage
#

filter_dir="$HOME/.config/rclone/filters"
sync_dir="$HOME/.sync"

if ! getent ahosts www.google.com >/dev/null; then
    printf "%s:      No internet connction. Aborting.\n" "$(date "+%Y-%m-%d %T")" >> "$logfile"
    exit
fi

case "$1" in
    --first-sync) opt="--first-sync" ;;
esac

while IFS= read line; do
    [ -z "$line" ] && continue
    [[ "$line" =~ ^# ]] && continue 

    IFS=':'
    fields=($line)
    remote=${fields[0]}
    remote_dir=${fields[1]}

    local_dir="$sync_dir/$remote/$remote_dir"
    filter_file="$(echo "$remote_dir" | tr ' /' '_.')"
    filter_file="$filter_dir/$remote/$filter_file"
    if [ -r "$filter_file" ]; then
        filter="--filters-file=$filter_file"
    else
        filter=
    fi

    printf "%s\n" "Syncing $remote:$remote_dir..."
    rclonesync $opt --verbose $filter "$remote:$remote_dir" "$local_dir"

done <<END
# remote:remote_dir
dropbox:Documents
dropbox:etc
dropbox:share
dropbox:src
dropbox:todo
onedrive:Boardgames/PQ-17
onedrive:Boardgames/Advanced Squad Leader
END

