#!/bin/sh

filter_dir="$HOME/.config/rclone/filters"
sync_dir="$HOME/.sync"

if ! getent ahosts www.google.com >/dev/null; then
    printf "%s:      No internet connction. Aborting.\n" "$(date "+%Y-%m-%d %T")" >> "$logfile"
    exit
fi

case $1 in
    --first-sync) opt="--first-sync" ;;
esac

while IFS= read -r line; do
    [ -z "$line" ] && continue
    case $line in \#*) continue ;; esac

    remote=$(echo "$line" | cut -d: -f1)
    remote_dir=$(echo "$line" | cut -d: -f2)

    local_dir="$sync_dir/$remote/$remote_dir"
    filter_file="$(echo "$remote_dir" | tr ' /' '_.')"
    filter_file="$filter_dir/$remote/$filter_file"
    if [ -r "$filter_file" ]; then
        filter="--filters-file=$filter_file"
    else
        filter=
    fi

    printf "%s\n" "Syncing $remote:$remote_dir..."
    rclonesync $opt --verbose "$filter" "$remote:$remote_dir" "$local_dir"

done <<END
# remote:remote_dir
dropbox:Documents
dropbox:etc
dropbox:share
dropbox:src
dropbox:todo
onedrive:Boardgames/PQ-17
onedrive:Boardgames/Advanced Squad Leader
END

