#!/bin/sh

filter_dir="$HOME/.config/rclone/filters"
sync_dir="$HOME/.sync"
logfile="$HOME/var/log/rclonesync.log"

if ! getent ahosts www.google.com >/dev/null; then
    printf "%s:      No internet connction. Aborting.\n" "$(date "+%Y-%m-%d %T")" >> "$logfile"
    exit
fi

case "$1" in
    --first-sync) opt="--first-sync" ;;
esac

while IFS= read line; do
    [ -z "$line" ] && continue
    [[ "$line" =~ ^# ]] && continue 

    IFS=':'
    fields=($line)
    remote=${fields[0]}
    remote_dir=${fields[1]}

    local_dir="$sync_dir/$remote/$remote_dir"
    filter_file="$(echo "$remote_dir" | tr ' /' '_.')"
    filter_file="$filter_dir/$remote/$filter_file"

    printf "%s\n" "Syncing $remote:$remote_dir..."
    # echo remote $remote
    # echo remote_dir $remote_dir
    # echo local_dir $local_dir
    # echo filter_file $filter_file
    # echo
    rclonesync $opt --verbose --filters-file="$filter_file" "$remote:$remote_dir" "$local_dir" #>> "$logfile" 2>&1

done <<END
# remote:remote_dir
dropbox:Documents
dropbox:etc
dropbox:share
dropbox:src
dropbox:todo
onedrive:Boardgames/PQ-17
onedrive:Boardgames/Advanced Squad Leader
END

