#!/bin/bash
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# (C) 2009 Ryan Tomayko <tomayko.com>
#
# abstract: dump 256 ansi colors to the terminal.
#

i=0
row=0
for i in $(seq 1 255); do
    newrow=$((i / 10))
    test $newrow -ne $row && echo
    row=$newrow
    printf "\e[38;5;%dm %03d \e[0m" "$i" "$i"
done

printf '\n\n     e.g., "\\e[38;5;136mTEXT\\e[0m" '
printf "\e[38;5;136m(for TEXT like this)\e[0m\n"

