#!/bin/bash
# Usage: colordump
# Dump 256 ansi colors to the terminal.
#
# (C) 2009 Ryan Tomayko <tomayko.com>

printf "How each ANSI color is displayed on your terminal:\n\n"

i=0
row=0
while [ $i -lt 255 ];
do
    newrow=$(expr $i / 10)
    test $newrow -ne $row && printf "\n"
    row=$newrow
    printf "\e[38;5;%dm %03d \e[0m" $i $i
    i=$(expr $i + 1)
done

printf '\n\n     e.g., "\\e[38;5;136mTEXT\\e[0m" '
printf "\e[38;5;136m(for TEXT like this)\e[0m\n"
