#!/usr/bin/env bash

if [[ ! "$1" || "$1" == "-h" || "$1" == "--help" ]]; then cat <<HELP
Curl a remote file into an editor.
http://benalman.com/

echo "Usage: $(basename "$0") [curloptions...] url"

Curl a remote file into the the current directory and open it in the editor of
your choice. The filename will be based on the URL's filename. If a file
name can't be determined from the URL, index.html will be used.

The editor will be auto-magically determined by stripping any leading "curl"
off this script's filename. For example, call this script "curlmate" and "mate"
will be run.

Copyright (c) 2012 "Cowboy" Ben Alman
Licensed under the MIT license.
http://benalman.com/about/license/
HELP
exit; fi

script="$(basename "$0")"
bin="${script#curl}"

# Create tempfile.
tmp="$(mktemp "/tmp/$script.XXXXX")"
# Curl (using all specified options) to tempfile, storing url for later.
echo -e 'Fetching file...\n'
url="$(curl "$@" -o "$tmp" -w '%{url_effective}')"
# Remove leading http:// or https:// from url, and add index.html at the end if
# filename can't be determined.
path="$(echo "$url" | perl -pe's#^https?://##i;s#/$|(^[^/\s]+|/[^/.\s]+)$#$1/index.html#')"

# Copy tempfile to final current directory
file=$(basename "$path")
mv "$tmp" "$file"

# Open file in editor!
echo -e "\nOpening ~${file#$HOME}"
exec "$bin" "$file"
