#!/bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2021 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract: pipe diff(1) to diff-so-fancy if it exists
#

if command -v diff-so-fancy >/dev/null; then
    /usr/bin/diff -u "$@" | diff-so-fancy
    (exit ${PIPESTATUS[0]}) # Exit with $? from diff
else
    /usr/bin/diff "$@"
fi

