#! /bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2022 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract: custom dmenu wrapper for anypinentry
#

LIBPATH="/usr/lib/dmenu:/usr/local/lib/dmenu:$HOME/lib/dmenu:$(dirname $0)"

oldifs="$IFS"
IFS=:
for d in $LIBPATH; do
    if [ -r "$d/routines.sh" ]; then
        dmenulib="$d/routines.sh"
        break
    fi
done
IFS="$oldifs"

if [ -n "${dmenulib-}" ]; then
    source "$dmenulib"
else
    printf "dmenu shell library not found\n" >&2
    exit 1
fi

if ! command -v anypinentry >/dev/null; then
    printf "anypinentry not found\n" >&2
    exit 1
fi

anypinentry "$@" --prompt "dmenu $(make_dmenu_args) -c -P -p \"\$AP_PROMPT\""

