#! /bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2022 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract: custom dmenu wrapper for anypinentry
#

PROGRAM=$(basename $0)
XRDB="$(xrdb -query | grep "$PROGRAM")"

getxres() {
    echo "$XRDB" | awk "/$PROGRAM.*$1/ {print \$2}"
}

make_dmenu_args() {
    font=$(getxres font)
    test -n "$font" && args="-fn $font $args"

    bg=$(getxres background)
    test -n "$bg" && args="-nb $bg $args"

    fg=$(getxres foreground)
    test -n "$fg" && args="-nf $fg $args"

    selbg=$(getxres selbackground)
    test -n "$selbg" && args="-sb $selbg $args"

    selfg=$(getxres selforeground)
    test -n "$selfg" && args="-sf $selfg $args"

    echo "$args"
}

if ! command -v anypinentry >/dev/null; then
    printf "anypinentry not found\n" >&2
    exit 1
fi

anypinentry "$@" --prompt "dmenu $(make_dmenu_args) -c -P -p \"\$AP_PROMPT\""

