#!/usr/bin/awk -f
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2014 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract: report double words
#
# Output: filename:lineno: word
#  (filename is - if reading stdin)

FILENAME != prevfile { # new file
    NR = 1             # reset line number
    prevfile = FILENAME
}

NF > 0 {
    if ($1 == lastword) # Check first word against last word of previous line
        printf "%s:%d: %s\n", FILENAME, NR, $1
    for (i = 2; i <= NF; i++) # Check each word with the previous word
        if ($i == $(i-1))
            printf "%s:%d: %s\n", FILENAME, NR, $i
    if (NF > 0) # Set lastword to last word on line
        lastword = $NF
 }

