#!/bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2014 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract: scan local network for Raspberry Pis
#
# Based on: https://gist.github.com/chr15m/8a79b891c680af3bff7704d3d3860fb4
#

pi_mac="b8:27:eb"

# get broadcast addresses for each network
nets=$(ip address show | awk '/inet / {printf "%s/%s", $4, gensub(".*/", "", 1, $2)}')

# loop over networks running the scan
for n in $nets; do
  # first find SSH machines silently to prime the arp table
  nmap -T4 -n -p 22 --open --min-parallelism 100 "$n/24" | grep -e "scan report for" -e "ssh" > /dev/null
  # timeout 0.25 bash -c "</dev/tcp/$ip/22" > /dev/null
done

# then run arp to show machines pi MACs
arp -na | grep "$pi_mac" | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'

