#!/bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2014 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract: scan local networks for Raspberry Pis
#
# Based on: https://gist.github.com/chr15m/8a79b891c680af3bff7704d3d3860fb4
#
pi_macs='28:cd:c1|2c:cf:67|3a:35:41|b8:27:eb|d8:3a:dd|dc:a6:32|e4:5f:01'

# Make sure MACs match the OUI
pi_macs=$(echo "$pi_macs" | sed -e 's/|/:..:..:..|/' -e 's/$/:..:..:../')

# scan each network
for n in $(ip -br a | awk '/^lo/ {next}; {print $3}'); do
  # find SSH machines silently to prime the arp table
  nmap -T5 -n -p 22 "$n" > /dev/null
done

# then search the arp table for Pi MACs and print the IP
arp -na |
   grep -iE "$pi_macs" |
   cut -d' ' -f2 |
   tr -d '()'

