#!/bin/sh

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2021 Jeremy Brubaker <јЬruЬаkе@оrіоnаrtѕ.іо>
#
# oneline - Print a one-line fortune. Tries to convert two-line
#     fortunes to one-liners if possible.
#
# Based on https://stackoverflow.com/a/36345272/3224379
#
# TODO: Add ability to print fortunes of n lines or less
# TODO: Make this a wrapper around fortune

# Defaults {{{1
#
DEFAULT_WIDTH=72
VERSION='1.0'

# Documentation {{{1
#
PROGNAME=$(basename $0)

print_help() {
    cat <<EOF
Usage: $PROGNAME [option]
Print a one-line fortune. Convert two-line fortunes to one-line if possible.
 
 -f FILE       get fortunes from FILE
 -w WIDTH      use WIDTH as the maximum line width (Default: $DEFAULT_WIDTH)
 -v            display version info and exit
 -h            display this help and exit
EOF
}

print_version() {
    cat <<EOF
$PROGNAME $VERSION
Copyright (C) 2021 Orion Arts
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Jeremy Brubaker.
EOF
}

# Process options {{{1
#
DEFAULT_WIDTH=72
cookie_file=
width=$DEFAULT_WIDTH

while getopts 'f:w:vh' opt; do
    case $opt in
        f) cookie_file=$OPTARG ;;
        w) width=$OPTARG ;;
        v) print_version; exit ;;
        h|?) print_help; exit ;;
    esac
done

# Generate fortune {{{1
#
while fortune -sn $width "$cookie_file" | awk -v width=$width '
    NR == 1 { L = $0 }
    NR == 2 && $1 == "--" {
        NR--
        $1 = " --"
        $0 = L $0
        if (length ($0) > width) {
            NR++
        }
    }
    END {
        if (NR == 1) {
            print
            exit 1
        }
    }'; do
    true
done

