#!/bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2014 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract: like expr(1), but uses Google's calculator to evaluate <expression>
#
# Usage: gxpr <expression>
#
# Math examples:
#   $ gxpr '1 + 1'
#   2
#
#   $ gxpr 2 ^  16
#   65536
#
#   $ gxpr '(2 ^ 1) + (2 ^ 2) + (2 ^ 3) + (2 ^ 5)'
#   46
#
#   $ gxpr '5*9+(sqrt 10)^3='
#   76.6227766
#
# Conversion examples:
#   $ gxpr 1GB in KB
#   1048576 kilobytes
#
#   $ gxpr 10 megabits in megabytes
#   1.25 megabytes
#
#   $ gxpr 2 miles in inches
#   126720 inches
#

CURL='curl -s --header User-Agent:gxpr/1.0'
SEARCH="https://www.google.com/search"
EXPR=$(echo "$@" | sed -e 's/+/%2B/g' -e 's/ /+/g')

res=$(
    $CURL "$SEARCH?q=$EXPR" |
    perl -ne '/<h2 class="r".*?>(.*)<\/h2>/ and print $1' |
    perl -ne '/= (.*)/ and print $1' |
    	perl -pe 's/[^\x00-\x7F]//g'
)

# if we don't have a result, assume it's an invalid expression
test -z "$res" && {
    echo "invalid expression:" "$@" 1>&2
    exit 1
}

echo "$res"

