#!/bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2014 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract: show HTTP headers for <url>
#
# Requires: curl or wget
#
# shellcheck disable=SC1090
. "$LIBSH"

@import stdlib
@import stdio

if stdlib::have curl; then
    cmd="curl -sv"
elif stdlib::have wget; then
    cmd="wget -qSO-"
else
    stdio::die 1 "Cannot find curl or wget. Exiting"
fi

[ -n "$1" ] ||
    stdio::die 1 "No url provided"

# Send stderr to stdout because that's what we're interested in
$cmd "$@" 2>&1 >/dev/null | 
	grep -v "^\*" |
	grep -v "^>" |
	grep -v "^{" |
	cut -c3-

