#!/bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2014 Jeremy Brubaker <jbru362@gmail.com>
#
################################################################################
# file:		hostdiscovery
# usage:	hostdiscovery
# abstract:	debian linux based host discovery script that captures info
#		about the hardware, software, network, configs, users, etc of 
#		a single host.
################################################################################

HOSTNAME=`hostname`
mkdir $HOSTNAME.results && cd $HOSTNAME.results

################################################################################
# stuff that could take a while
################################################################################

# grab the config files
{ 	echo -e "\033[1;32mCopying /etc/... \033[0m"			;
	cp -a /etc/ . 2>/dev/null					&&
	echo -e "\033[1;32mCopying /etc/ Succeeded. \033[0m"		||
	echo -e "\033[1;31mCopying /etc/ Failed. \033[0m" 		; } &

# grab the log files
{ 	echo -e "\033[1;32mCopying /var/log/... \033[0m"		;
	cp -a /var/log/ . 2>/dev/null					&&
	echo -e "\033[1;32mCopying /var/log/ Succeeded. \033[0m"	||
	echo -e "\033[1;31mCopying /var/log/ Failed. \033[0m" 		; } &

# grab the website if available
{ 	echo -e "\033[1;32mCopying /var/www/... \033[0m"		;
	cp -a /var/www/ . 2>/dev/null					&&
	echo -e "\033[1;32mCopying /var/www/ Succeeded. \033[0m"	||
	echo -e "\033[1;31mCopying /var/www/ Failed. \033[0m" 		; } &

# grab the locate database
{ 	echo -e "\033[1;32mCopying mlocate.db... \033[0m"		;
	{ updatedb ; cp /var/lib/mlocate/mlocate.db . 2>/dev/null ; }	&&
	echo -e "\033[1;32mCopying mlocate.db Succeeded. \033[0m"	||
	echo -e "\033[1;31mCopying mlocate.db Failed. \033[0m" 		; } &

# grab the mysql database
{ service mysql start && mysqldump --all-databases > $HOSTNAME.mysql ; } &

# grab all files ending in .conf and store them in a directory hierarchy
{
	mkdir conf ; cd conf ; 
	for FILE in `find / -name *.conf` ; do 
		cp --parents $FILE . 2>/dev/null ; 
	done ; 
	cd .. ;
} &


################################################################################
# Hardware
################################################################################
mkdir hardware && cd hardware

echo -e "\033[1;33mBeginning hardware discovery of $HOSTNAME... \033[0m"

# what make/model of machine?
# what serial number?
echo -e "\033[1;33mMake sure you photograph the machine to get make/model, ports, etc.\033[0m"

echo "Manufacturer: `dmidecode -s system-manufacturer`"		| tee    hardwareinfo.out
echo "Product Name: `dmidecode -s system-product-name`"		| tee -a hardwareinfo.out
echo "Serial Number: `dmidecode -s system-serial-number`" 	| tee -a hardwareinfo.out
echo "BIOS Vendor: `dmidecode -s bios-vendor`"			| tee -a hardwareinfo.out
echo "BIOS Version: `dmidecode -s bios-version`"		| tee -a hardwareinfo.out
echo "BIOS Release Date: `dmidecode -s bios-release-date`" 	| tee -a hardwareinfo.out
# ...

# what type of CPU?
lscpu								| tee lscpu.out
cp /proc/cpuinfo .

# how much ram total / used?
free -th							| tee free.out
cp /proc/meminfo .

# how much hard drive space total / used?
df -h								| tee df.out

# which partitions are mounted? size? partition type?
mount								| tee mount.out
cp /proc/partitions .

# what usb devices were connected?
lsusb								| tee lsusb.out

# what pci devices were connected?
lspci								| tee lspci.out

# other hardware stuff...
lshal 								> lshal.out
dmidecode							> dmidecode.out

echo -e "\033[1;33mFinished hardware discovery of $HOSTNAME... \033[0m"

cd ..

################################################################################
# software
################################################################################
mkdir software && cd software

echo -e "\033[1;33mBeginning software discovery of $HOSTNAME... \033[0m"

# kernel version?
# distribution?
uname -a 						| tee uname.out
cp /proc/version .
lsb_release -a						> lsb_release.out

# which software packages were installed?
dpkg -l							> dpkg.out
apt-cache dump						> apt-cache-dump.out

# what processes are currently running?
ps aufxw						| tee psafuxw.out

# what web server / version was installed?
apache2 -v						| tee apache.out
nginx -v						| tee nginx.out

# what database server / version was installed? running?
mysql -V						| tee mysql.out

# which other network services were installed? running?
netstat -pant | grep LISTEN				| tee netstat-pant-listen.out

netstat -n						> netstat.out

echo -e "\033[1;33mFinished software discovery of $HOSTNAME... \033[0m"

cd ..
	
################################################################################
# network
################################################################################
mkdir network && cd network

# ip address
# subnet mask
# mac address
ifconfig -a							| tee ifconfig.out

# show the routing table
route -n							| tee route.out
netstat -rn							> netstat-rn.out

# show wireless information
iwconfig							| tee iwconfig.out

# what nameservers does might machine commonly access?
cp /etc/resolv.conf .

# what other hosts/ips might this machine commonly access?
arp -a								| tee arp.out

# what other machine was connected to this one? on what service? from what ip address?
netstat -pant | grep ESTABLISHED				| tee netstat-pant-established.out

cd ..

################################################################################
# users
################################################################################
mkdir users && cd users

echo -e "\033[1;33mBeginning user discovery of $HOSTNAME... \033[0m"

# which users have a password set?  did you retrieve the password hashes?
cp /etc/{passwd,shadow,group} .

# which users have logged in previously?
last								| tee last.out

# what other user was logged in when you were logged in?
who								| tee who.out

# which user had files stored in their home directory? did you retrieve them?
du /home/ -h --max-depth 1					| tee home-du.out

# which user had a mozilla profile? did you retrieve cookies / stored settings / history / etc?
################################################################################
# grab user files of interest in /home
################################################################################
for USER in `ls /home` ; do
	
	mkdir $USER && cd $USER
	
	cp /home/$USER/.bash_history		./bash_history		2>/dev/null
	cp /home/$USER/.bash_logout		./bash_logout		2>/dev/null
	cp /home/$USER/.bashrc			./bashrc		2>/dev/null
	cp /home/$USER/.profile			./profile		2>/dev/null
	
	cp -a /home/$USER/.config		./config		2>/dev/null
	cp -a /home/$USER/.local		./local			2>/dev/null
	cp -a /home/$USER/.mozilla		./mozilla		2>/dev/null

	cp -a /home/$USER/.cache/google-chrome	./cache-google-chrome	2>/dev/null
	cp -a /home/$USER/.config/google-chrome	./config-google-chrome	2>/dev/null

	cp -a /home/$USER/.ssh			./ssh			2>/dev/null

	cd ..

done
################################################################################
# grab user files of interest in /root
################################################################################

mkdir root && cd root
	
	cp /root/.bash_history			./bash_history		2>/dev/null
	cp /root/.bash_logout			./bash_logout		2>/dev/null
	cp /root/.bashrc			./bashrc		2>/dev/null
	cp /root/.profile			./profile		2>/dev/null
	
	cp -a /root/.config			./config		2>/dev/null
	cp -a /root/.local			./local			2>/dev/null
	cp -a /root/.mozilla			./mozilla		2>/dev/null

	cp -a /root/.cache/google-chrome	./cache-google-chrome	2>/dev/null
	cp -a /root/.config/google-chrome	./config-google-chrome	2>/dev/null

	cp -a /root/.ssh			./ssh			2>/dev/null

cd ..

echo -e "\033[1;33mFinished software discovery of $HOSTNAME... \033[0m"

cd ..

################################################################################
# odball stuff and cleanup
################################################################################

cd ..

