#!/bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2023 Jeremy Brubaker <orionarts.io>
#
# abstract: print the absolute path of the target of a symbolic link
#
# Usage: linkpath LINK
#
# shellcheck disable=SC1090
. "$LIBSH"

@import stdlib
@import error
@import stdio

if [ $# -ne 1 ]; then
    stdio::die 1 "%s: missing operand" "$0"
fi

stdlib::realpath "$1"
case $? in
    0) exit ;;
    *) stdio::die 1 "%s: %s: %s" "$0" "$1" "$(error::strerror "$?")" ;;
esac

