#!/bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2015 Ray Donnelly <https://stackoverflow.com/users/3257826/ray-donnelly>
#
# abstract: print the absolute path of the target of a symbolic link
#
# Usage: linkpath LINK

realfile=$( ls -l $1 | awk '{print $11}' )
startdir=$( dirname $1 )

printf "%s\n" $( cd $startdir/$( dirname $realfile); pwd )/$( basename $realfile )

