#!/bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2014 Jeremy Brubaker <jbru362@gmail.com>
#

# NAME   : mkthumbs - script to scale images down
#
# USAGE  : mkthumbs [dir] [scalefac]
#
# INPUTS : [dir]      -> the directory with jpg files
#          [scalefac] -> the factor to scale them down by
#
# OUTPUTS: scaled down .thumb.jpg files of same basename
#
# EXAMPLE: to scale down your cwd .jpg's by a factor of 8:
#          % ./mkthumbs . 8
#
# $Id: mkthumbs,v 1.0 2001.01.28 14:50:59 tkralidi Exp $

if [ $# -ne 2 ]; then
    echo "Usage: $0 [dir] [scalefac]"
    exit 1
fi

DJPEG=`which djpeg`
CJPEG=`which cjpeg`

echo "Working on .jpg files in $1"

cd $1
for i in *.jpg; do
    if [ -f $i ]; then
        echo "Scaling $i by $2"
        $DJPEG -scale 1/$2 $i | $CJPEG > th.$i
        echo "th.$i created"
    else
        echo "No files in $1 of type .jpg"
        echo "Exiting"
        exit 2
    fi
done

echo "Done"

exit 0

