#!/bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2014 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract: create image thumbnails
#
# USAGE  : mkthumbs [dir] [scalefac]
#
# INPUTS : [dir]      -> the directory with jpg files
#          [scalefac] -> the factor to scale them down by
#
# OUTPUTS: scaled down .thumb.jpg files of same basename
#
# EXAMPLE: to scale down your cwd .jpg's by a factor of 8:
#          % ./mkthumbs . 8
#
# shellcheck disable=SC1090
. "$LIBSH"

@import stdio
@import stdlib

[ $# -eq 2 ] || stdio::die 1 "Usage: %s [dir] [scalefac]" "$0"

for b in djpeg cjpeg; do
    stdlib::have "$b" || stdio::die 1 "'%s' is required" "$b"
done

for i in "$1"/*.jpg; do
    if [ -f "$i" ]; then
        printf "Scaling %s by %s..." "$i" "$2"
        djpeg -scale "1/$2" "$i" | cjpeg > "$1/th.$i"
        printf "th.%s created\n" "$i"
    else
        stdio::die 2 "No JPEG files in %s. Exiting" "$1"
    fi
done

