#!/bin/sh
#
# news: print the latest news
#
# -l list news items only

#cd /usr/etc/news # Find news

case $1 in
    -l) list=1 ;; # list only
esac

IFS='
' # Gracefully handle a missing ~/.news_time

for i in `ls -t * $HOME/.news_time 2>&1` # Sort news and timestamp by MTIME
do
    IFS=' ' # Split ls on spaces
    case $i in
        'ls: cannot access'*) ;; # Skip missing files
        */.news_time) break ;; # Everything else has been read
        *)
            set X`ls -l $i` # Get newsfile info
                            # (leading X deals with leading - in ls output)

            echo "$i: ($3) $6 $7 $8" # filename: (user) date time

            # Print news item unless -l specified
            if test -z $list
            then
                cat $i
                echo
            fi
    esac
done

# All news has been read unless -l specified
test -z $list &&  touch $HOME/.news_time

