#!/bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2014 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract: print the latest news
#
# -l, --list list news items only
#
newsdir=${NEWSDIR:-/var/lib/news}
newstime=${XDG_STATE_HOME}/misc/news_time

if ! [ -d "$newsdir" ]; then
    printf 'newsdir not found: %s\n' "$newsdir" >&2
    exit 1
fi

case $1 in
    -l | --list) list=1 ;; # list only
esac

for f in $( (find "$newsdir" -mindepth 1 -printf "%T+\t%p\n";
    find "$(dirname "$newstime")" -maxdepth 1 -name "$(basename "$newstime")" -printf "%T+\t%p\n") \
                 | sort -r | cut -f2); do

    case $f in
        "$newstime") break ;; # Everything else has been read
        *)
            find "$newsdir" -name "$(basename "$f")" -printf "%p: (%u) %t\n"

            # Print news item unless -l specified
            if test -z $list; then
                cat "$f"
                echo
            fi
    esac
done

# All news has been read unless -l specified
test -z $list &&  touch "$newstime"

