#!/bin/bash

# openurl
#
# Open an URL in browser
#
# Uses environment variable $BROWSER as follows:
#
# firefox -> firefx (opens new tab) This is the default
# chrome  -> Google Chrome
# links   -> links
# glinks  -> links -g
# elinks  -> elinks
#
# Expects: URL to open. You can open local files simply
#          by passing the filename as the arguemt to openurl
#

# TODO: See about making this a function

# See if args are a local file first
if [ -f "$1" ]; then
    url="file://$1"
# Otherwise assume its a web URL
else
    url=$1
fi

# Run user's selected browser
case "$BROWSER" in
    # Google Chrome
    chrome)
        chrome $url &
        ;;

    # Console links
    elinks)
        elinks $url
        ;;

    links)
        links $url
        ;;

    # Graphical links
    glinks)
        case "$TERM" in
            # In VTY use links -g
            # FIXME: What is $TERM under ssh?
            linux)
                links -g $url
                ;;
            # Running under X
            *)
                exec links -g $url &
                ;;
        esac
        ;;

    # firefox
    # This is the default
    firefox|*)
        # Use `which mozilla` so we don't keep
        # calling this function.
        # (I did it before it OOM'd on me)
        `which mozilla` -remote "ping()" 2> /dev/null

        # $? == 0 if mozilla is running
        # $? == 2 if mozilla is not running
        if [ $? -eq 2 ]; then
            # Open a new window if mozilla is not running
            exec `which mozilla` "$url" &
        else
            # Open a new tab if mozilla is running
            exec `which mozilla` -remote "openurl($url, new-tab)"
        fi
        ;;
esac
