#!/bin/bash
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2014 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract: open a URL in $BROWSER
#
# Expects: URL to open. You can open local files simply
#          by passing the filename as the arguemt to openurl
#

# See if args are a local file first
if [ -f "$1" ]; then
    url="file://$1"
# Otherwise assume its a web URL
else
    url=$1
fi

case "$BROWSER" in
    # Graphical links
    glinks)
        case "$TERM" in
            # In VTY use links -g
            linux)
                links -g $url
                ;;
            # Remote shell
            putty*)
                links -g $url
                ;;
            # Running under X
            *)
                exec links -g $url &
                ;;
        esac
        ;;

    $BROWSER|*)
        $BROWSER $url
        ;;
esac

