#!/bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2014 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract: rename <file(s)> to <file(s)>.orig
#

if [ $# = 0 ] ; then
    printf "usage: orig FILE ..." >&2
    printf "copy FILE(s) to FILE.orig" >&2
else
    for f in "$@"; do
        dest="$(dirname "$f")/$(basename "$f").orig"

        cp -pr "$f" "$dest"
        printf "copied '%s' -> '%s'\n" "$f" "$dest"
    done
fi

