#!/usr/bin/awk -f
#
# check /etc/passwd for errors

BEGIN { FS = ":" }

NF != 7 {
    printf("%d: wrong number of fields: %s\n", NR, $0)
    next }

$1 ~ /[^A-Za-z0-9-]/ {
    printf("%d: non-alphanumeric username: %s\n", NR, $1) }

$2 != "x" {
    printf("%d: user %s has no shadow password\n", NR, $1) }

$3 ~ /[^0-9]/ {
    printf("%d: user %s has non-numeric UID: %s\n", NR, $1, $3) }

$4 ~ /[^0-9]/ {
    printf("%d: user %s has non-numeric GID: %s\n", NR, $1, $4) }

$6 !~ /^\// {
    printf("%d: user %s has invalid login directory: %s\n", NR, $1, $6) }


