#!/usr/bin/env bash
#
# `passmenu` is a dmenu-based interface to pass, the standard Unix
# password manager. This design allows you to quickly copy a password to the
# clipboard without having to open up a terminal window if you don't already
# have one open.
#
# If `--type` is specified, the password is typed using xdotool
# instead of copied to the clipboard.
#
# Usage
#
#     passmenu [--type] [dmenu arguments...]
#
# [dmenu]: http://tools.suckless.org/dmenu/
# [xdotool]: http://www.semicomplete.com/projects/xdotool/
# [pass]: http://www.zx2c4.com/projects/password-store/
#
# https://git.zx2c4.com/password-store/tree/contrib/dmenu/passmenu
#

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
    typeit=1
    shift
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | dmenu -l 10 $DMENU_OPTS "$@")

[[ -n $password ]] || exit

if [[ $typeit -eq 0 ]]; then
    pass show -c "$password" 2>/dev/null
else
    pass show "$password" | { IFS= read -r pass; printf %s "$pass"; } |
        xdotool type --clearmodifiers --file -
fi
