#!/usr/bin/awk -f
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2014 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract: check a file in /etc/passwd format for errors
#

BEGIN { FS = ":" }

NF != 7 {
    printf("%d: wrong number of fields: %s\n", NR, $0)
    next }

$1 ~ /[^A-Za-z0-9-]/ {
    printf("%d: non-alphanumeric username: %s\n", NR, $1) }

$2 != "x" {
    printf("%d: user %s has no shadow password\n", NR, $1) }

$3 ~ /[^0-9]/ {
    printf("%d: user %s has non-numeric UID: %s\n", NR, $1, $3) }

$4 ~ /[^0-9]/ {
    printf("%d: user %s has non-numeric GID: %s\n", NR, $1, $4) }

$6 !~ /^\// {
    printf("%d: user %s has invalid login directory: %s\n", NR, $1, $6) }

