#!/bin/bash
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2014 Jeremy Brubaker <jbru362@gmail.com>
#
# pick: interactively select arguments and print them to stdout
#
# Select words from command line arguments or
# from stdin if no command line args or first arg is -

fd=0 # read interactive input from stdin by default

# If args are on stdin set up a connection
# to the tty for interactive input
#
if test "$1" = '-' || test $# -eq 0
then
    fd=3
    exec 3</dev/tty
fi

while :
do
    # Read next arg based on where
    # interactive input comes from
    case $fd in
        0) arg=$1; shift ;; # input on stdin; read $*
        3) read arg ;; # input on fd 3; read stdin
    esac

    # Quit if out of args
    test "$arg" || break;

    echo -n "$arg? " >/dev/tty

    read -u $fd response
    case $response in
        [yY]*) echo $arg ;;
        [qQ]*) break ;;
    esac
done

