#!/usr/bin/sh

# Copyright (c) 2006 SUSE LINUX Products GmbH, Nuernberg, Germany.
# Copyright (c) 2009 Fedora Project
# Copyright (c) 2014-2015 Red Hat
# This file and all modifications and additions to the pristine
# package are under the same license as the package itself (at bottom of file)
#
# Please submit bugfixes or comments via http://bugzilla.redhat.com/
#
# Anna Bernathova <anicka@novell.com> 2006
# Pavel Nemec <pnemec@novell.com> 2006
# Rex Dieter <rdieter@fedoraproject.org> 2009
# Pavol Rusnak <prusnak@novell.com> 2009
# Boris Ranto <branto@redhat.com> 2014
#
# use proper binary (pinentry-qt, pinentry-gnome, pinentry-gtk-2 or pinentry-curses)
#
# abstract: pinentry wrapper
#   modified from the original to include pinentry-dmenu

kde_running=
gnome_running=
arg=
display=
# look for a --display option
for opt in "$@"; do
    if [ "$opt" = "--display" ]; then
        arg=1
    elif [ -n "$arg" ]; then
        display="$opt"
    else
        arg=
    fi
done

# export DISPLAY if pinentry is meant to be run on a different display
# check the KDE_FULL_SESSION variable otherwise
if [ -n "$display" ] && [ "$DISPLAY" != "$display" ]; then
    export DISPLAY="$display"
elif [ -n "$KDE_FULL_SESSION" ]; then
    kde_running=1
elif [ -n "$GNOME_SETUP_DISPLAY" ]; then
    gnome_running=1
fi

# Check for presence of xprop binary
type xprop >/dev/null 2>/dev/null
XPROP=$?

if [ -n "$DISPLAY" ] && [ $XPROP -eq 0 ]; then
    xprop -root | grep "^KDE_FULL_SESSION" >/dev/null 2>/dev/null
    if test $? -eq 0; then
        kde_running=1
    fi
fi

# if a user supplied a pinentry binary, use it
if [ -n "$PINENTRY_BINARY" ];
then
	export PINENTRY_BINARY="$PINENTRY_BINARY"
# if KDE is detected and pinentry-qt exists, use pinentry-qt
elif [ -n "$kde_running" ] && [ -x /usr/bin/pinentry-qt ]
then
	export PINENTRY_BINARY="/usr/bin/pinentry-qt"
# otherwise if GNOME is detected and pinentry-gnome3 exists, use pinentry-gnome3
elif [ -n "$gnome_running" ] && [ -x /usr/bin/pinentry-gnome3 ]
then
	export PINENTRY_BINARY="/usr/bin/pinentry-gnome3"
# otherwise test if pinentry-dmenu is installed
elif [ -n "$DISPLAY" ] && command -v pinentry-dmenu >/dev/null;
then
	export PINENTRY_BINARY="pinentry-dmenu"
# otherwise test if pinentry-gtk-2 is installed
elif [ -n "$DISPLAY" ] && [ -x /usr/bin/pinentry-gtk-2 ]
then
	export PINENTRY_BINARY="/usr/bin/pinentry-gtk-2"
# otherwise test if pinentry-qt exists although KDE is not detected
elif [ -n "$DISPLAY" ] && [ -x /usr/bin/pinentry-qt ]
then
	export PINENTRY_BINARY="/usr/bin/pinentry-qt"
# use pinentry-tty if installed
elif [ -x /usr/bin/pinentry-tty ]
then
	export PINENTRY_BINARY="/usr/bin/pinentry-tty"
# pinentry-curses is installed by default
else
    export PINENTRY_BINARY="/usr/bin/pinentry-curses"
fi
$PINENTRY_BINARY "$@"

# Original license:
#
# Copyright Fedora Project Authors.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
#     COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
#     WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR
#     IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#     SOFTWARE.

