#! /bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2022 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract: custom dmenu wrapper for anypinentry
#
# shellcheck disable=SC1090
. "$LIBSH"

@import dmenu
@import stdio
@import stdlib

stdlib:have pinentry-any || stdio::die 1 "pinentry-any not found"

pinentry-any "$@" --prompt "dmenu $(dmenu::make_args) -c -P -p \"\$AP_PROMPT\""

