#!/bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2014 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract:	hasty portscan script when nmap is not available

HOST=$1
PORTSFILE=$2

printf "\033[1;32mstarting portscan of $HOST using portfile '$PORTSFILE'...\033[0m\n"
printf "# portscan of $HOST using portfile $PORTSFILE ... "  > $HOST.scan
printf "# start: $(date)"                                   >> $HOST.scan

for PORT in $(cat $PORTSFILE); do 
	printf "trying $HOST:$PORT..."

	ISOPEN=$(nc -vzw 3 $HOST $PORT 2>&1 | grep Connected | wc -l)

	if [ $ISOPEN == "1" ] ; then
		printf "\033[1;32mopen\033[0m"
		printf "$HOST:$PORT" >> $HOST.scan ;
	fi 
    echo
done

printf "# end: $(date)" >> $HOST.scan

