#!/bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2014 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract: send stdin to stdout and stderr
#
# Usage: ppeek [<prefix>]
# Read lines from standard input and write to both standard output and
# standard error. This is useful for peeking in on a pipeline.
#
set -e
prefix="${1:-> }"
while read -r line
do echo "$line"
   echo "$prefix$line" 1>&2
done
exit 0

