#!/bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2014 Jeremy Brubaker <jbru362@gmail.com>
#
################################################################################
# file:		ppingsweep
# date:		21 Aug 14
# usage:	ppingsweep first.three.octets
#		ex. # pingsweep 192.168.1
# abstract:	Hasty parrallel pingsweep script when nmap is not available.
################################################################################

NETWORK=$1

echo -e "\033[1;32mstarting pingsweep of $NETWORK.0 ...\033[0m"
echo "# pingsweep of $NETWORK.0 ... "		> $NETWORK.0.sweep
echo "# start: `date`"				>> $NETWORK.0.sweep

for HOST in `seq 1 254` ; do 

{

	echo -n "." ;

	ISALIVE=`ping -c 1 $NETWORK.$HOST | grep received | cut -d " " -f 4` ; 

	if [ $ISALIVE == "1" ] ; then

		echo -en "\033[1;32m.\033[0m"
		echo "$NETWORK.$HOST" 		>> $NETWORK.0.sweep ;

	fi ; } &

done

echo "# end: `date`" >> $NETWORK.0.sweep
echo -e "\033[1;32mdone.\033[0m"

