#!/bin/sh
################################################################################
# file:		ppingsweep.sh
# date:		21 Aug 14
# usage:	./ppingsweep.sh first.three.octets
#		ex. # ./pingsweep 192.168.1
# abstract:	Hasty parrallel pingsweep script when nmap is not available.
################################################################################

NETWORK=$1

echo -e "\033[1;32mstarting pingsweep of $NETWORK.0 ...\033[0m"
echo "# pingsweep of $NETWORK.0 ... "		> $NETWORK.0.sweep
echo "# start: `date`"				>> $NETWORK.0.sweep

for HOST in `seq 1 254` ; do 

{

	echo -n "." ;

	ISALIVE=`ping -c 1 $NETWORK.$HOST | grep received | cut -d " " -f 4` ; 

	if [ $ISALIVE == "1" ] ; then

		echo -en "\033[1;32m.\033[0m"
		echo "$NETWORK.$HOST" 		>> $NETWORK.0.sweep ;

	fi ; } &

done

echo "# end: `date`" >> $NETWORK.0.sweep
echo -e "\033[1;32mdone.\033[0m"

