#!/bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2014 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract: perform a reverse zone transfer
#
if [ "$#" -lt 1 ]; then
    echo "Usage: raxfr domain"
    exit;
fi

ns=`host -t ns $1 | cut -d' ' -f4`
arpaaddr=`rlook $ns | cut -d' ' -f1 | cut -d. -f2-`
host -la $arpaaddr

