#!/bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2014 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract: take a screenshot
#

DIR="$HOME/var/lib/screenshot"
LOGDIR="$HOME/var/log"

mkdir -p "$DIR"
mkdir -p "$LOGDIR"

DATE="$(date +%Y%m%d@%H%M%S)"
NAME="${DIR}/screenshot-${DATE}.png"
LOG="${DIR}/screenshot.log"

# Check for GraphicsMagick
if command -v gm; then
    IMPORT="gm import"
elif command -v import; then
    IMPORT="import"
else
    printf "GraphicsMagic or ImageMagick required but not found.\n" >&2

# Check if the dir to store screenshots exists
if [ ! -d "$DIR" ]; then mkdir -p "$DIR"; fi

# Screenshot a selected window
if [ "$1" = "win" ]; then $IMPORT "$NAME"; fi

# Screenshot the entire screen
if [ "$1" = "scr" ]; then $IMPORT -window root "$NAME"; fi

# Screenshot a selected area
if [ "$1" = "area" ]; then $IMPORT "$NAME"; fi

if [[ $# = 0 ]]; then
    # Display a warning if no area defined
    echo "No screenshot area has been specified. Screenshot not taken."
    echo "${DATE}: No screenshot area has been defined. Screenshot not taken." >> "$LOG"
else
    # Save the screenshot in the directory and edit yhe log
    echo "$NAME" >> "$LOG"
fi

