#!/bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2021 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract: digitally sign a file with a SSH key
#
# Usage: sign <filename> [<path/to/ssh/key>] (defaults to ~/.ssh/id_ed25519 then
#   ~/.ssh/id_rsa
#

if [ -z "$1" ]; then
    printf "No filename to sign provided. Exiting\n" >&2
    exit 1
fi

if [ -z "$2" ]; then
    key="$HOME/.ssh/id_rsa"
else
    key="$2"
fi

ssh-keygen -Y sign -f "$key" -n file "$1"

