#!/bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2025 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract: Pass stdin to $BROWSER
#

if ! command -v mktemp >/dev/null; then
    printf "'mktemp' not found!\n" >&2
    exit 1
fi

if ! command -v "$BROWSER" >/dev/null; then
    printf "'$BROWSER' is invalid (set to '%s'\n" "$BROWSER" >&2
    exit 1
fi

tmp=$(mktemp)
trap 'rm -- "$tmp"' EXIT

cat > "$tmp"

"$BROWSER" "$tmp"

# Pause so the browser can open the temp file before it's deleted
sleep 1

