#!/bin/bash
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2023 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract: hack around packer-plugin-lxc Issue #5
#     (https://github.com/hashicorp/packer-plugin-lxc/issues/5)
# Source: https://github.com/hashicorp/packer-plugin-lxc/issues/5#issuecomment-927375007

if [[ "${@: -1}" == "./rootfs" ]]; then
    # Override params to drop rootfs
	set -- "${@:1:1}" "${2}/rootfs" "${@:3:2}" "--exclude=./dev/log" "${@:6:$(($# - 5 - 1 ))}" "." 

	echo "Running tar in lxc namespace: '${@}'"

    # Run the original command in uid/gid mapped enviroment - root mapped uid
    # must have write permission in output director
	lxc-usernsexec -m b:0:1000:1 -m b:1:100001:65535 -- /usr/bin/tar ${@}
else
    # Handles non-export commands 
	/usr/bin/tar ${@}
fi

