#!/bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2025 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract: run a command in a tmux popup
#
# Search all but last arg for custom switches
unset args tmux k
for i in $( seq $(($#-1)) ); do
    # Custom switches
    case $1 in
        -k) k='stty -icanon min 1 time 0; dd bs=1 count=1'; shift; continue ;;
        -t) tmux=1; shift; continue ;;
    esac

    args="$args $1"
    shift
done

# The last arg (all that is left) is the command to run
cmd="$1;$k"

# Run in a tmux session if asked to allow scrolling
if [ -n "$tmux" ]; then
    cmd="tmux new-session -A -s scratch \"$cmd\" \; set-option status off"
fi

tmux display-popup -E $args "$cmd"

# Return true to avoid the annoying extra
# window that says the popup command failed
true

