#!/usr/bin/awk -f
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2020 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract: test terminal true color capability
#

BEGIN {
    s="/\\/\\/\\/\\/\\";
    s=s s s s s s s s;
    for (colnum = 0; colnum < 77; colnum++) {
        r = 255 - (colnum * 255 / 76);
        g = (colnum * 510 / 76);
        b = (colnum * 255 / 76);
        if (g > 255) g = 510 - g;
        printf "\33[48;2;%d;%d;%dm", r, g, b;
        printf "\33[38;2;%d;%d;%dm", 255 - r, 255 - g, 255 - b;
        printf "%s\033[0m", substr (s, colnum + 1, 1);
    }
    printf "\n";
}

