#!/bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2025 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract: Convert HTML of vim syntax highlighting
#
# Defaults {{{1
#
BACKGROUND_DFLT=light
LINENO_DFLT=0
SHOW_FOLDS_DFLT=0
FONT_DFLT=monospace

# Documentation {{{1
#
VERSION='1.0'

print_help() {
    [ -n "$2" ] && printf "%s\n" "$2"
    cat <<EOF
Usage: $0 [OPTION] FILE...

Convert HTML of vim syntax highlighting

Options: 
 -c [COLORSCHEME] use COLORSCHEME (Default: from ~/.vimrc)
 -b [dark|light]  set background (Default: $BACKGROUND_DFLT)
 -l               turn on line numbers
 -d               show folds
 -f [FONT]        use FONT instead of the default ($FONT_DFLT)
 -V               display version info and exit
 -h               display this help and exit
EOF
} >&2

print_version() {
    cat <<EOF
$PROGNAME $VERSION
Copyright (C) 2025 Orion Arts
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Jeremy Brubaker.
EOF
}

# Process Options {{{1
#
background=$BACKGROUND_DFLT
lineno=$LINENO_DFLT
ignore_folds=$IGNORE_FOLDS_DFLT
show_folds=$SHOW_FOLDS_DFLT
font=$FONT_DFLT
colorscheme=
while getopts 'c:b:ldf:Vh' opt; do
    case $opt in
        c) colorscheme=$OPTARG ;;
        b) case $OPTARG in
               light|white|l|w) background=light ;;
               dark|black|b|d)  background=dark ;;
               *) printf 'Invalid background: %s\n' "$OPTARG" >&2; exit 1 ;;
           esac ;;
        l) lineno=1 ;;
        d) show_folds=1 ;;
        f) font=$OPTARG ;;
        V) print_version; exit ;;
        h) print_help; exit ;;
        h|?) print_help; exit 1 ;;
    esac
done
shift $((OPTIND - 1))
OPTIND=1

# Main {{{1
#
for f in $@; do
    vim \
        +"syntax on | set background=$background" \
        ${colorscheme:++"colorscheme $colorscheme"} \
        +'let g:html_no_progress=1' \
        +"let g:html_number_lines=$lineno" \
        +"let g:html_dynamic_folds=$show_folds" \
        +'let g:html_prevent_copy="fn"' \
        +"let g:html_font='$font'" \
        +'runtime! syntax/2html.vim' \
        +wq +q "$f"
done

