#!/bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2014 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract: periodically report who has logged on and logged out
#

new=/tmp/wwho1.$$
old=/tmp/wwho2.$$

case $* in
    -h)
        cat 1>&2 << USAGE
Usage: watchwho [OPTION]
Report logon activity

  -i  do not report current logons
  -h  display this help and exit
USAGE
        exit 1
        ;;
    -i) who >$old ;;
    *) >$old ;;
esac

trap 'rm -f $new $old; exit 1' 1 2 15

while :
do
    who >$new
    diff $old $new
    mv $new $old
    sleep 10
done | awk '/>/ { $1 = "in:\t"; print }
            /</ { $1 = "out:\t"; print }'

