#! /bin/sh
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2021 Jeremy Brubaker <jbru362@gmail.com>
#
# abstract: display a fortune cookie in an X dialog
#

bg=$(xrdb -query | awk '/xfortune\.fg/ {print $2}')
fg=$(xrdb -query | awk '/xfortune\.bg/ {print $2}')

# NOTE: using -center puts it in the center of multiple screens
args="-buttons OK -default OK -geometry +500+500 -file -"

command -v xmessage  >/dev/null && xmessage=xmessage
command -v gxmessage >/dev/null && xmessage=gxmessage

if test -n "$xmessage"; then
    case $xmessage in
        gxmessage)
            font=$(xrdb -query | awk '/xfortune\.gfont/ {print $2}')
            font=${font:-20}
            args="$args -borderless -ontop"
            ;;
        xmessage)
            font=$(xrdb -query | awk '/xfortune\.xfont/ {print $2}')
            font=${font:-"-*-*-*-*-*-*-20-0-0-0-p-*-*-*"}
            args="$args"
            ;;
    esac
    fortune "$@" | $xmessage ${font:+-fn "$font"} ${fg:+-fg "$fg"} ${bg:+-bg "$bg"} $args
fi

