#! /bin/sh

type 2>&1 >/dev/null xmessage  && xmessage=xmessage
type 2>&1 >/dev/null gxmessage && xmessage=gxmessage

if test -n "$xmessage"; then
    case $xmessage in
        gxmessage)
            font="20"
            args="-borderless -ontop"
            ;;
        xmessage)
            font="-*-*-*-*-*-*-20-0-0-0-p-*-*-*"
            args=
            ;;
    esac
    fortune "$@" | $xmessage ${font:+-fn "$font"} $args -center -file -
fi

