#!/usr/bin/python

# Convert an alacrity config file to support Xresources color scheme
#
# Based on https://github.com/MuntashirAkon/dotfiles/blob/master/.local/bin/alacritty_xr_color_scheme

import os
from pathlib import Path
import subprocess
import tomllib

file = "xresources.toml"
output = Path(file)

if "XDG_CONFIG_HOME" in os.environ and os.path.isfile(Path(os.environ["XDG_CONFIG_HOME"]) / "alacritty"):
    output = Path(os.environ["XDG_CONFIG_HOME"]) / "alacritty" / output
elif "XDG_CONFIG_HOME" in os.environ and os.path.isfile(Path(os.environ["XDG_CONFIG_HOME"]) / "alacritty"):
    output = Path(os.environ["XDG_CONFIG_HOME"]) / output
elif os.path.isfile(Path(os.environ["HOME"]) / ".config/alacritty"):
    output = Path(os.environ["HOME"]) / ".config/alacritty" / output
else:
    file = Path("." + file)
    output = Path(os.environ["HOME"]) / file

def getresource(resource):
    return subprocess.Popen(['xrdb', '-get', resource.encode('utf-8')], \
            stdout=subprocess.PIPE).communicate()[0].decode("utf-8").strip('\n')

with open(output, "w") as f:
    f.write(f"""
[colors.primary]
background = "{getresource('alacritty.background')}"
foreground = "{getresource('alacritty.foreground')}"

[colors.normal]
black = "{getresource('alacritty.color0')}"
red = "{getresource('alacritty.color1')}"
green = "{getresource('alacritty.color2')}"
yellow = "{getresource('alacritty.color3')}"
blue = "{getresource('alacritty.color4')}"
magenta = "{getresource('alacritty.color5')}"
cyan = "{getresource('alacritty.color6')}"
white = "{getresource('alacritty.color7')}"

[colors.bright]
black = "{getresource('alacritty.color8')}"
red = "{getresource('alacritty.color9')}"
green = "{getresource('alacritty.color10')}"
yellow = "{getresource('alacritty.color11')}"
blue = "{getresource('alacritty.color12')}"
magenta = "{getresource('alacritty.color13')}"
cyan = "{getresource('alacritty.color14')}"
white = "{getresource('alacritty.color15')}"

[colors.cursor]
text = "{getresource('alacritty.background')}"
cursor = "{getresource('alacritty.cursorColor')}"

[colors.vi_mode_cursor]
text = "{getresource('alacritty.background')}"
cursor = "{getresource('alacritty.cursorColor')}"

[font]
size = {int(getresource('alacritty.font').split(':size=')[1])}

[font.normal]
family = "{getresource('alacritty.font').split(':')[0]}"
""")

